//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.23 at 07:53:32 �ߌ� JST 
//


package jp.co.nskint.uq.pd.signage.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://uq.nskint.co.jp/uqSignage/layout>ComponentType">
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="data" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_caption" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scale_caption" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scale_max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="scale_min" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="scale_step" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="orientation" type="{http://uq.nskint.co.jp/uqSignage/layout}OrientationType" default="vertical" />
 *       &lt;attribute name="bar_width" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="bar_margin" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "bar_graph")
public class BarGraph
    extends ComponentType
{

    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlAttribute
    protected String data;
    @XmlAttribute(name = "data_caption", required = true)
    protected String dataCaption;
    @XmlAttribute(name = "scale_caption", required = true)
    protected String scaleCaption;
    @XmlAttribute(name = "scale_max")
    protected Integer scaleMax;
    @XmlAttribute(name = "scale_min")
    protected Integer scaleMin;
    @XmlAttribute(name = "scale_step")
    protected Integer scaleStep;
    @XmlAttribute
    protected OrientationType orientation;
    @XmlAttribute(name = "bar_width")
    protected Integer barWidth;
    @XmlAttribute(name = "bar_margin")
    protected Integer barMargin;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the dataCaption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCaption() {
        return dataCaption;
    }

    /**
     * Sets the value of the dataCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCaption(String value) {
        this.dataCaption = value;
    }

    /**
     * Gets the value of the scaleCaption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScaleCaption() {
        return scaleCaption;
    }

    /**
     * Sets the value of the scaleCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScaleCaption(String value) {
        this.scaleCaption = value;
    }

    /**
     * Gets the value of the scaleMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScaleMax() {
        return scaleMax;
    }

    /**
     * Sets the value of the scaleMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScaleMax(Integer value) {
        this.scaleMax = value;
    }

    /**
     * Gets the value of the scaleMin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScaleMin() {
        return scaleMin;
    }

    /**
     * Sets the value of the scaleMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScaleMin(Integer value) {
        this.scaleMin = value;
    }

    /**
     * Gets the value of the scaleStep property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getScaleStep() {
        if (scaleStep == null) {
            return  1;
        } else {
            return scaleStep;
        }
    }

    /**
     * Sets the value of the scaleStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScaleStep(Integer value) {
        this.scaleStep = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link OrientationType }
     *     
     */
    public OrientationType getOrientation() {
        if (orientation == null) {
            return OrientationType.VERTICAL;
        } else {
            return orientation;
        }
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrientationType }
     *     
     */
    public void setOrientation(OrientationType value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the barWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBarWidth() {
        return barWidth;
    }

    /**
     * Sets the value of the barWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBarWidth(Integer value) {
        this.barWidth = value;
    }

    /**
     * Gets the value of the barMargin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBarMargin() {
        return barMargin;
    }

    /**
     * Sets the value of the barMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBarMargin(Integer value) {
        this.barMargin = value;
    }

}
