//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 03:51:44 �ߌ� JST 
//


package jp.co.nskint.uq.pd.signage.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://uq.nskint.co.jp/uqSignage/layout}components"/>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="target_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="interval" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "html",
    "text",
    "marquee",
    "table",
    "pieGraph",
    "barGraph",
    "lineGraph",
    "image",
    "audio",
    "video",
    "streamVideo"
})
@XmlRootElement(name = "change_component", namespace = "http://uq.nskint.co.jp/uqSignage/timeline")
public class ChangeComponent {

    protected Html html;
    protected Text text;
    protected Marquee marquee;
    protected Table table;
    @XmlElement(name = "pie_graph")
    protected PieGraph pieGraph;
    @XmlElement(name = "bar_graph")
    protected BarGraph barGraph;
    @XmlElement(name = "line_graph")
    protected LineGraph lineGraph;
    protected Image image;
    protected Audio audio;
    protected Video video;
    @XmlElement(name = "stream_video")
    protected StreamVideo streamVideo;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String name;
    @XmlAttribute(name = "target_id", required = true)
    protected String targetId;
    @XmlAttribute
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;
    @XmlAttribute
    @XmlSchemaType(name = "unsignedInt")
    protected Long interval;

    /**
     * Gets the value of the html property.
     * 
     * @return
     *     possible object is
     *     {@link Html }
     *     
     */
    public Html getHtml() {
        return html;
    }

    /**
     * Sets the value of the html property.
     * 
     * @param value
     *     allowed object is
     *     {@link Html }
     *     
     */
    public void setHtml(Html value) {
        this.html = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setText(Text value) {
        this.text = value;
    }

    /**
     * Gets the value of the marquee property.
     * 
     * @return
     *     possible object is
     *     {@link Marquee }
     *     
     */
    public Marquee getMarquee() {
        return marquee;
    }

    /**
     * Sets the value of the marquee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Marquee }
     *     
     */
    public void setMarquee(Marquee value) {
        this.marquee = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link Table }
     *     
     */
    public Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link Table }
     *     
     */
    public void setTable(Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the pieGraph property.
     * 
     * @return
     *     possible object is
     *     {@link PieGraph }
     *     
     */
    public PieGraph getPieGraph() {
        return pieGraph;
    }

    /**
     * Sets the value of the pieGraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link PieGraph }
     *     
     */
    public void setPieGraph(PieGraph value) {
        this.pieGraph = value;
    }

    /**
     * Gets the value of the barGraph property.
     * 
     * @return
     *     possible object is
     *     {@link BarGraph }
     *     
     */
    public BarGraph getBarGraph() {
        return barGraph;
    }

    /**
     * Sets the value of the barGraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link BarGraph }
     *     
     */
    public void setBarGraph(BarGraph value) {
        this.barGraph = value;
    }

    /**
     * Gets the value of the lineGraph property.
     * 
     * @return
     *     possible object is
     *     {@link LineGraph }
     *     
     */
    public LineGraph getLineGraph() {
        return lineGraph;
    }

    /**
     * Sets the value of the lineGraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineGraph }
     *     
     */
    public void setLineGraph(LineGraph value) {
        this.lineGraph = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link Image }
     *     
     */
    public Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image }
     *     
     */
    public void setImage(Image value) {
        this.image = value;
    }

    /**
     * Gets the value of the audio property.
     * 
     * @return
     *     possible object is
     *     {@link Audio }
     *     
     */
    public Audio getAudio() {
        return audio;
    }

    /**
     * Sets the value of the audio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Audio }
     *     
     */
    public void setAudio(Audio value) {
        this.audio = value;
    }

    /**
     * Gets the value of the video property.
     * 
     * @return
     *     possible object is
     *     {@link Video }
     *     
     */
    public Video getVideo() {
        return video;
    }

    /**
     * Sets the value of the video property.
     * 
     * @param value
     *     allowed object is
     *     {@link Video }
     *     
     */
    public void setVideo(Video value) {
        this.video = value;
    }

    /**
     * Gets the value of the streamVideo property.
     * 
     * @return
     *     possible object is
     *     {@link StreamVideo }
     *     
     */
    public StreamVideo getStreamVideo() {
        return streamVideo;
    }

    /**
     * Sets the value of the streamVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamVideo }
     *     
     */
    public void setStreamVideo(StreamVideo value) {
        this.streamVideo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the targetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * Sets the value of the targetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetId(String value) {
        this.targetId = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInterval(Long value) {
        this.interval = value;
    }

}
