//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.14 at 07:21:40 �ߌ� JST
//


package jp.co.nskint.uq.pd.signage.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for layout element declaration.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="layout">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;group ref="{http://uq.nskint.co.jp/uqSignage/layout}components" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *         &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "components"
})
@XmlRootElement(name = "layout")
public class LayoutXml {

    @XmlElements({
        @XmlElement(name = "audio", type = Audio.class),
        @XmlElement(name = "image", type = Image.class),
        @XmlElement(name = "table", type = Table.class),
        @XmlElement(name = "html", type = Html.class),
        @XmlElement(name = "stream_video", type = StreamVideo.class),
        @XmlElement(name = "video", type = Video.class),
        @XmlElement(name = "text", type = Text.class),
        @XmlElement(name = "line_graph", type = LineGraph.class),
        @XmlElement(name = "pie_graph", type = PieGraph.class),
        @XmlElement(name = "bar_graph", type = BarGraph.class),
        @XmlElement(name = "marquee", type = Marquee.class)
    })
    protected List<ComponentType> components;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    @XmlSchemaType(name = "unsignedShort")
    protected Integer height;
    @XmlAttribute
    @XmlSchemaType(name = "unsignedShort")
    protected Integer width;

    /**
     * Gets the value of the components property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the components property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponents().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Audio }
     * {@link Image }
     * {@link Table }
     * {@link Html }
     * {@link StreamVideo }
     * {@link Video }
     * {@link Text }
     * {@link LineGraph }
     * {@link PieGraph }
     * {@link BarGraph }
     * {@link Marquee }
     *
     *
     */
    public List<ComponentType> getComponents() {
        if (components == null) {
            components = new ArrayList<ComponentType>();
        }
        return this.components;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the height property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setWidth(Integer value) {
        this.width = value;
    }

}
