//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.23 at 07:53:32 �ߌ� JST 
//


package jp.co.nskint.uq.pd.signage.model.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jp.co.nskint.uq.pd.signage.model.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jp.co.nskint.uq.pd.signage.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BarGraph }
     * 
     */
    public BarGraph createBarGraph() {
        return new BarGraph();
    }

    /**
     * Create an instance of {@link StreamVideo }
     * 
     */
    public StreamVideo createStreamVideo() {
        return new StreamVideo();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link PieGraph }
     * 
     */
    public PieGraph createPieGraph() {
        return new PieGraph();
    }

    /**
     * Create an instance of {@link Block }
     * 
     */
    public Block createBlock() {
        return new Block();
    }

    /**
     * Create an instance of {@link Html }
     * 
     */
    public Html createHtml() {
        return new Html();
    }

    /**
     * Create an instance of {@link Marquee }
     * 
     */
    public Marquee createMarquee() {
        return new Marquee();
    }

    /**
     * Create an instance of {@link ChangeComponent }
     * 
     */
    public ChangeComponent createChangeComponent() {
        return new ChangeComponent();
    }

    /**
     * Create an instance of {@link Video }
     * 
     */
    public Video createVideo() {
        return new Video();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link LayoutXml }
     * 
     */
    public LayoutXml createLayoutXml() {
        return new LayoutXml();
    }

    /**
     * Create an instance of {@link TimeLineXml }
     * 
     */
    public TimeLineXml createTimeLineXml() {
        return new TimeLineXml();
    }

    /**
     * Create an instance of {@link LineGraph }
     * 
     */
    public LineGraph createLineGraph() {
        return new LineGraph();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link Audio }
     * 
     */
    public Audio createAudio() {
        return new Audio();
    }

}
