//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.02 at 07:43:37 ŒßŒã JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uq.nskint.co.jp/uqSignage/layout", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jp.co.nskint.uq.pd.signage.model.xml;
