//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 11:01:34 �ߌ� JST 
//


package jp.co.nskint.uq.pd.signage.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://uq.nskint.co.jp/uqSignage/layout>ComponentType">
 *       &lt;attribute name="data" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_caption" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="legend_position" type="{http://uq.nskint.co.jp/uqSignage/layout}DirectionType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "pie_graph")
public class PieGraph
    extends ComponentType
{

    @XmlAttribute(required = true)
    protected String data;
    @XmlAttribute(name = "data_caption", required = true)
    protected String dataCaption;
    @XmlAttribute(name = "legend_position")
    protected DirectionType legendPosition;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the dataCaption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCaption() {
        return dataCaption;
    }

    /**
     * Sets the value of the dataCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCaption(String value) {
        this.dataCaption = value;
    }

    /**
     * Gets the value of the legendPosition property.
     * 
     * @return
     *     possible object is
     *     {@link DirectionType }
     *     
     */
    public DirectionType getLegendPosition() {
        return legendPosition;
    }

    /**
     * Sets the value of the legendPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectionType }
     *     
     */
    public void setLegendPosition(DirectionType value) {
        this.legendPosition = value;
    }

}
